/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/mustang-1969.glb 
Author: vecarz (https://sketchfab.com/heynic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ford-mustang-john-bowe-1969-wwwvecarzcom-91a5454aaf02492a9c7e959b8eb6db9f
Title: Ford Mustang John Bowe 1969 | www.vecarz.com
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/mustang-1969.glb");

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_6.geometry} material={materials.blue} />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.material}
        />
        <mesh geometry={nodes.Object_10.geometry} material={materials.white} />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.LicPlate_black}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.LicPlate_blue}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.LicPlate_white}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials.LicPlate_yellow}
        />
        <mesh geometry={nodes.Object_20.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.black} />
        <mesh
          geometry={nodes.Object_56.geometry}
          material={materials.brakedisk}
        />
        <mesh
          geometry={nodes.Object_58.geometry}
          material={materials.brakedisk}
        />
        <mesh geometry={nodes.Object_60.geometry} material={materials.carpaint}>
          <meshStandardMaterial
            color={props.color}
            metalness={0.6}
            roughness={0.2}
          />
        </mesh>
        <mesh geometry={nodes.Object_62.geometry} material={materials.carpaint}>
          <meshStandardMaterial
            color={props.color}
            metalness={0.6}
            roughness={0.2}
          />
        </mesh>
        <mesh geometry={nodes.Object_64.geometry} material={materials.carpaint}>
          <meshStandardMaterial
            color={props.color}
            metalness={0.6}
            roughness={0.2}
          />
        </mesh>
        <mesh geometry={nodes.Object_66.geometry} material={materials.carpaint}>
          <meshStandardMaterial
            color={props.color}
            metalness={0.6}
            roughness={0.2}
          />
        </mesh>
        <mesh geometry={nodes.Object_68.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_70.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_78.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_82.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_84.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_86.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_88.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_90.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_92.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_94.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_96.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_98.geometry} material={materials.chrome} />
        <mesh
          geometry={nodes.Object_100.geometry}
          material={materials.chrome}
        />
        <mesh
          geometry={nodes.Object_102.geometry}
          material={materials.chrome}
        />
        <mesh
          geometry={nodes.Object_104.geometry}
          material={materials.chrome}
        />
        <mesh
          geometry={nodes.Object_106.geometry}
          material={materials.clearglass}
        />
        <mesh
          geometry={nodes.Object_108.geometry}
          material={materials.clearglass}
        />
        <mesh
          geometry={nodes.Object_110.geometry}
          material={materials.clearglass}
        />
        <mesh
          geometry={nodes.Object_112.geometry}
          material={materials.clearglass}
        />
        <mesh
          geometry={nodes.Object_114.geometry}
          material={materials.interior}
        />
        <mesh
          geometry={nodes.Object_116.geometry}
          material={materials.interior}
        />
        <mesh
          geometry={nodes.Object_118.geometry}
          material={materials.mirror}
        />
        <mesh
          geometry={nodes.Object_120.geometry}
          material={materials.orangeglass}
        />
        <mesh
          geometry={nodes.Object_122.geometry}
          material={materials.redglass}
        />
        <mesh
          geometry={nodes.Object_124.geometry}
          material={materials.redglass}
        />
        <mesh
          geometry={nodes.Object_126.geometry}
          material={materials.material_15}
        />
        <mesh
          geometry={nodes.Object_128.geometry}
          material={materials.material_15}
        />
        <mesh
          geometry={nodes.Object_130.geometry}
          material={materials.material_15}
        />
        <mesh
          geometry={nodes.Object_132.geometry}
          material={materials.material_15}
        />
        <mesh
          geometry={nodes.Object_134.geometry}
          material={materials.material_15}
        />
        <mesh
          geometry={nodes.Object_136.geometry}
          material={materials.material_15}
        />
        <mesh
          geometry={nodes.Object_138.geometry}
          material={materials.material_15}
        />
        <mesh
          geometry={nodes.Object_140.geometry}
          material={materials.material_15}
        />
        <mesh
          geometry={nodes.Object_142.geometry}
          material={materials.material_15}
        />
        <mesh geometry={nodes.Object_144.geometry} material={materials.tire} />
        <mesh
          geometry={nodes.Object_146.geometry}
          material={materials.windowglass}
        />
      </group>
    </group>
  );
}
