/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/mustang-2017-gt.glb 
Author: IsaacOldton (https://sketchfab.com/IsaacOldton)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2017-ford-mustang-gt-7dfe5e8c4198432385f596a780c043a3
Title: 2017 Ford Mustang GT
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/mustang-2017-gt.glb");

  return (
    <group {...props} dispose={null}>
      <group rotation={[0, Math.PI, 0]}>
        <group rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01}>
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials.Black_Metal_Paint}
          />
          <mesh
            geometry={nodes.Object_5.geometry}
            material={materials.Black_Metal_Paint}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01}>
          <mesh
            geometry={nodes.Object_33.geometry}
            material={materials.CARPAINT}
          >
            <meshStandardMaterial
              color={props.color}
              metalness={0.6}
              roughness={0.2}
            />
          </mesh>
          <mesh
            geometry={nodes.Object_34.geometry}
            material={materials.CARPAINT}
          >
            <meshStandardMaterial
              color={props.color}
              metalness={0.6}
              roughness={0.2}
            />
          </mesh>
        </group>
        <group rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01}>
          <mesh
            geometry={nodes.Object_46.geometry}
            material={materials.Black_Plastic}
          />
          <mesh
            geometry={nodes.Object_47.geometry}
            material={materials.Black_Plastic}
          />
          <mesh
            geometry={nodes.Object_48.geometry}
            material={materials.Black_Plastic}
          />
          <mesh
            geometry={nodes.Object_49.geometry}
            material={materials.Black_Plastic}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01}>
          <mesh
            geometry={nodes.Object_55.geometry}
            material={materials.Light}
          />
          <mesh
            geometry={nodes.Object_56.geometry}
            material={materials.Window_Glass}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01}>
          <mesh
            geometry={nodes.Object_62.geometry}
            material={materials.Rubber_Black}
          />
          <mesh
            geometry={nodes.Object_63.geometry}
            material={materials.Rubber_Black}
          />
          <mesh
            geometry={nodes.Object_64.geometry}
            material={materials.Rubber_Black}
          />
          <mesh
            geometry={nodes.Object_65.geometry}
            material={materials.Rubber_Black}
          />
        </group>
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.Black_Plastic}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.Black_Metal_Paint}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.Calipers}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.Chrome}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials.Chrome}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials.Indicator}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials.Chrome}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Object_21.geometry}
          material={materials.GlassTransparent}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Object_23.geometry}
          material={materials.Mirror}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Object_25.geometry}
          material={materials.Brushed_Aluminum}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Object_27.geometry}
          material={materials.Light}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Object_29.geometry}
          material={materials.Black_Plastic}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Object_31.geometry}
          material={materials.Black_Plastic}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Object_36.geometry}
          material={materials.Window_Glass}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Object_38.geometry}
          material={materials.Chrome}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Object_40.geometry}
          material={materials.Black_Plastic}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Object_42.geometry}
          material={materials.Indicator}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Object_44.geometry}
          material={materials.BackThingy}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Object_51.geometry}
          material={materials.Chrome}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Object_53.geometry}
          material={materials.Front_Glass}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Object_58.geometry}
          material={materials.RedGlass}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Object_60.geometry}
          material={materials.Chrome}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.01}
        />
      </group>
    </group>
  );
}
