/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/mustang-2005.glb 
Author: Ricy (https://sketchfab.com/ngon_3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2005-ford-mustang-gt-26b6b60cf2804370ac3c64424242dc1f
Title: 2005 Ford Mustang GT
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/mustang-2005.glb");

  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]} scale={0.025}>
          <group
            position={[0.32, 21.021, 29.99]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
          >
            <group position={[-73.064, -16.795, -0.32]}>
              <mesh
                geometry={nodes.body_Carpaint_Flakes_Ruby_0.geometry}
                material={materials.Carpaint_Flakes_Ruby}
              >
                <meshStandardMaterial
                  color={props.color}
                  metalness={0.6}
                  roughness={0.2}
                />
              </mesh>
              <mesh
                geometry={nodes.body_Car_Plastics_0.geometry}
                material={materials.Car_Plastics}
              />
              <mesh
                geometry={nodes["body_Material_#1332_0"].geometry}
                material={materials.Material_1332}
              />
            </group>
          </group>
          <group
            position={[0.37, -71.928, 24.379]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
          >
            <group position={[19.885, -11.183, -0.37]}>
              <mesh
                geometry={nodes.headlight_housing_Aluminium_Clean1_0.geometry}
                material={materials.Aluminium_Clean1}
              />
              <mesh
                geometry={nodes.headlight_housing_Car_Plastics_0.geometry}
                material={materials.Car_Plastics}
              />
              <mesh
                geometry={nodes.headlight_housing_Glass_Clear_0.geometry}
                material={materials.Glass_Clear}
              />
              <mesh
                geometry={nodes["headlight_housing_Material_#1636_0"].geometry}
                material={materials.Material_1636}
              />
              <mesh
                geometry={nodes.headlight_housing_MainMat_0.geometry}
                material={materials.MainMat}
              />
            </group>
          </group>
          <group
            position={[0.302, 75.716, 31.808]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
          >
            <group position={[-132.577, -18.613, -0.302]}>
              <mesh
                geometry={nodes.tailight_Glass_Clear_0.geometry}
                material={materials.Glass_Clear}
              />
              <mesh
                geometry={nodes.tailight_redglass_0.geometry}
                material={materials.redglass}
              />
              <mesh
                geometry={nodes.tailight_Car_Plastics_0.geometry}
                material={materials.Car_Plastics}
              />
              <mesh
                geometry={nodes["tailight_Material_#78_0"].geometry}
                material={materials.Material_78}
              />
              <mesh
                geometry={nodes.tailight_reddrk_0.geometry}
                material={materials.reddrk}
              />
            </group>
          </group>
          <group
            position={[31.864, -51.968, 13.278]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
            scale={[1.01, 1.01, 1.268]}
          >
            <group position={[-1.918, -7.572, 1.382]}>
              <mesh
                geometry={nodes["FrdPerofrmcRim_Material_#205_0"].geometry}
                material={materials.Material_205}
              />
              <mesh
                geometry={nodes.FrdPerofrmcRim_Aluminium_Clean2_0.geometry}
                material={materials.Aluminium_Clean2}
              />
              <mesh
                geometry={nodes.FrdPerofrmcRim_Aluminium_Clean3_0.geometry}
                material={materials.Aluminium_Clean3}
              />
            </group>
          </group>
          <group
            position={[29.08, -51.962, 13.239]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
            scale={[1, 1, 1.095]}
          >
            <mesh
              geometry={nodes.tire_rubbr1_0.geometry}
              material={materials.rubbr1}
            />
            <mesh
              geometry={nodes.tire_rubbr2_0.geometry}
              material={materials.rubbr2}
            />
          </group>
          <group
            position={[0.349, 16.099, 41.762]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
          >
            <mesh
              geometry={nodes.glass_Glass_Clear_0.geometry}
              material={materials.Glass_Clear}
              position={[-68.142, -28.567, -0.349]}
            />
          </group>
          <group
            position={[0.343, 79.9, 32.263]}
            rotation={[-1.369, 0, Math.PI]}
            scale={[1.387, 1.384, 1.018]}
          >
            <mesh
              geometry={nodes.rearbadge_Aluminium_Clean0_0.geometry}
              material={materials.Aluminium_Clean0}
            />
            <mesh
              geometry={nodes["rearbadge_Material_#1648_0"].geometry}
              material={materials.Material_1648}
            />
            <mesh
              geometry={nodes["rearbadge_Material_#274_0"].geometry}
              material={materials.Material_274}
            />
          </group>
          <group
            position={[-6.049, -29.659, 34.78]}
            scale={[2.354, 1.677, 1.677]}
          >
            <mesh
              geometry={nodes.intdash_Car_Plastics_0.geometry}
              material={materials.Car_Plastics}
            />
            <mesh
              geometry={nodes["intdash_Material_#217_0"].geometry}
              material={materials.Material_217}
            />
            <mesh
              geometry={nodes.intdash_Leather_Top_Grain_Black_0.geometry}
              material={materials.Leather_Top_Grain_Black}
            />
            <mesh
              geometry={nodes["intdash_Material_#1344_0"].geometry}
              material={materials.Material_1344}
            />
            <mesh
              geometry={nodes["intdash_Material_#205_0"].geometry}
              material={materials.Material_205}
            />
          </group>
          <group
            position={[22.13, -19.104, 33.687]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={0.328}
          >
            <mesh
              geometry={nodes["vents_Material_#217_0"].geometry}
              material={materials.Material_217}
            />
            <mesh
              geometry={nodes.vents_Aluminium_Clean1_0.geometry}
              material={materials.Aluminium_Clean1}
            />
          </group>
          <group
            position={[16.342, -22.259, 34.12]}
            scale={[2.354, 1.677, 1.677]}
          >
            <mesh
              geometry={nodes["GaugeDashBoard_Material_#1416_0"].geometry}
              material={materials.Material_1416}
              position={[-9.513, -4.412, 0.394]}
            />
          </group>
          <group
            position={[14.543, -22.793, 33.551]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={[1.226, 1.226, 1.385]}
          >
            <mesh
              geometry={nodes["gauges_Material_#450_0"].geometry}
              material={materials.Material_450}
              position={[-3.687, 0.18, -0.395]}
            />
          </group>
          <group
            position={[14.546, -13.087, 31.092]}
            rotation={[-1.309, 0, Math.PI]}
            scale={[1.087, 1.087, 34.221]}
          >
            <group position={[0, 0, -0.098]}>
              <mesh
                geometry={nodes["msngsteeringwheel_Material_#437_0"].geometry}
                material={materials.Material_437}
              />
              <mesh
                geometry={nodes.msngsteeringwheel_Car_Plastics_0.geometry}
                material={materials.Car_Plastics}
              />
              <mesh
                geometry={nodes["msngsteeringwheel_Material_#217_0"].geometry}
                material={materials.Material_217}
              />
              <mesh
                geometry={nodes["msngsteeringwheel_Material_#844_0"].geometry}
                material={materials.Material_844}
              />
              <mesh
                geometry={nodes["msngsteeringwheel_Material_#857_0"].geometry}
                material={materials.Material_857}
              />
            </group>
          </group>
          <group
            position={[28.722, -21.625, 28.967]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
          >
            <group position={[-30.417, -15.772, -28.722]}>
              <mesh
                geometry={nodes.leftdoor_Carpaint_Flakes_Ruby_0.geometry}
                material={materials.Carpaint_Flakes_Ruby}
              >
                <meshStandardMaterial
                  color={props.color}
                  metalness={0.6}
                  roughness={0.2}
                />
              </mesh>
              <mesh
                geometry={nodes.leftdoor_Car_Plastics_0.geometry}
                material={materials.Car_Plastics}
              />
              <mesh
                geometry={nodes.leftdoor_Leather_Top_Grain_Black_0.geometry}
                material={materials.Leather_Top_Grain_Black}
              />
              <mesh
                geometry={nodes["leftdoor_Material_#217_0"].geometry}
                material={materials.Material_217}
              />
              <mesh
                geometry={nodes["leftdoor_Material_#1511_0"].geometry}
                material={materials.Material_1511}
              />
              <mesh
                geometry={nodes.leftdoor_Glass_Mirror1_0.geometry}
                material={materials.Glass_Mirror1}
              />
              <mesh
                geometry={nodes.leftdoor_Aluminium_Clean_0.geometry}
                material={materials.Aluminium_Clean}
              />
              <mesh
                geometry={nodes.leftdoor_Glass_Clear_0.geometry}
                material={materials.Glass_Clear}
              />
              <mesh
                geometry={nodes["leftdoor_Material_#1534_0"].geometry}
                material={materials.Material_1534}
              />
            </group>
          </group>
          <group
            position={[0.32, 13.578, 49.207]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
          >
            <mesh
              geometry={nodes.roof_Carpaint_Flakes_Ruby_0.geometry}
              material={materials.Carpaint_Flakes_Ruby}
              position={[-65.621, -36.012, -0.32]}
            >
              <meshStandardMaterial
                color={props.color}
                metalness={0.6}
                roughness={0.2}
              />
            </mesh>
          </group>
          <group
            position={[0.32, -34.477, 34.959]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
          >
            <mesh
              geometry={nodes.hood_Carpaint_Flakes_Ruby_0.geometry}
              material={materials.Carpaint_Flakes_Ruby}
              position={[-17.566, -21.764, -0.32]}
            >
              <meshStandardMaterial
                color={props.color}
                metalness={0.6}
                roughness={0.2}
              />
            </mesh>
          </group>
          <group
            position={[0.32, -48.467, 22.333]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
          >
            <mesh
              geometry={nodes.fenders_Carpaint_Flakes_Ruby_0.geometry}
              material={materials.Carpaint_Flakes_Ruby}
              position={[-3.576, -9.138, -0.32]}
            >
              <meshStandardMaterial
                color={props.color}
                metalness={0.6}
                roughness={0.2}
              />
            </mesh>
          </group>
          <group
            position={[0.32, -73.898, 18.363]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
          >
            <group position={[21.855, -5.168, -0.32]}>
              <mesh
                geometry={
                  nodes.msngv6front_bumper_Carpaint_Flakes_Ruby_0.geometry
                }
                material={materials.Carpaint_Flakes_Ruby}
              >
                <meshStandardMaterial
                  color={props.color}
                  metalness={0.6}
                  roughness={0.2}
                />
              </mesh>
              <mesh
                geometry={nodes.msngv6front_bumper_Car_Plastics_0.geometry}
                material={materials.Car_Plastics}
              />
              <mesh
                geometry={nodes.msngv6front_bumper_Glass_Clear_0.geometry}
                material={materials.Glass_Clear}
              />
              <mesh
                geometry={nodes["msngv6front_bumper_Material_#288_0"].geometry}
                material={materials.Material_288}
              />
              <mesh
                geometry={nodes["msngv6front_bumper_Material_#287_0"].geometry}
                material={materials.Material_287}
              />
            </group>
          </group>
          <group
            position={[0.32, 71.684, 20.207]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
          >
            <group position={[-123.727, -7.012, -0.32]}>
              <mesh
                geometry={
                  nodes.msngv6rearbumper_Carpaint_Flakes_Ruby_0.geometry
                }
                material={materials.Carpaint_Flakes_Ruby}
              >
                <meshStandardMaterial
                  color={props.color}
                  metalness={0.6}
                  roughness={0.2}
                />
              </mesh>
              <mesh
                geometry={nodes.msngv6rearbumper_Glass_Clear_0.geometry}
                material={materials.Glass_Clear}
              />
              <mesh
                geometry={nodes["msngv6rearbumper_Material_#314_0"].geometry}
                material={materials.Material_314}
              />
            </group>
          </group>
          <group
            position={[0.32, 64.687, 38.155]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
          >
            <group position={[-116.73, -24.96, -0.32]}>
              <mesh
                geometry={nodes.trunk_Carpaint_Flakes_Ruby_0.geometry}
                material={materials.Carpaint_Flakes_Ruby}
              >
                <meshStandardMaterial
                  color={props.color}
                  metalness={0.6}
                  roughness={0.2}
                />
              </mesh>
              <mesh
                geometry={nodes.trunk_tintedglass_0.geometry}
                material={materials.tintedglass}
              />
              <mesh
                geometry={nodes["trunk_Material_#1380_0"].geometry}
                material={materials.Material_1380}
              />
            </group>
          </group>
          <group
            position={[0.32, 21.021, 29.99]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
          >
            <mesh
              geometry={nodes.inttop_Car_Plastics_0.geometry}
              material={materials.Car_Plastics}
              position={[-73.064, -16.795, -0.32]}
            />
          </group>
          <group
            position={[-0.008, -17.015, 21.531]}
            rotation={[0.175, Math.PI / 2, 0]}
            scale={[0.281, 0.281, 0.239]}
          >
            <group position={[-4.303, 0, -3.91]}>
              <mesh
                geometry={nodes["shifter_Material_#217_0"].geometry}
                material={materials.Material_217}
              />
              <mesh
                geometry={nodes.shifter_Car_Plastics_0.geometry}
                material={materials.Car_Plastics}
              />
              <mesh
                geometry={nodes.shifter_Aluminium_Clean_0.geometry}
                material={materials.Aluminium_Clean}
              />
            </group>
          </group>
          <group
            position={[0.864, 3.209, 26.229]}
            scale={[0.155, 0.155, 0.195]}
          >
            <group position={[101.37, -14.472, -86.904]}>
              <mesh
                geometry={nodes["fseats_Material_#205_0"].geometry}
                material={materials.Material_205}
              />
              <mesh
                geometry={nodes.fseats_Car_Plastics_0.geometry}
                material={materials.Car_Plastics}
              />
            </group>
          </group>
          <group position={[0.062, 31.559, 33.347]} scale={0.134}>
            <mesh
              geometry={nodes["rseats_Material_#205_0"].geometry}
              material={materials.Material_205}
              position={[107.991, -18.055, -47.118]}
            />
          </group>
          <group
            position={[0.066, -20.942, 25.749]}
            scale={[2.354, 1.677, 1.677]}
          >
            <group position={[-2.598, -5.197, 5.384]}>
              <mesh
                geometry={nodes["dashmid_Material_#205_0"].geometry}
                material={materials.Material_205}
              />
              <mesh
                geometry={nodes.dashmid_Aluminium_Clean_0.geometry}
                material={materials.Aluminium_Clean}
              />
              <mesh
                geometry={nodes["dashmid_Material_#672_0"].geometry}
                material={materials.Material_672}
              />
            </group>
          </group>
          <group
            position={[14.395, -18.521, 31.939]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[1.321, 1.464, 1.464]}
          >
            <group position={[3.987, -0.455, -0.114]}>
              <mesh
                geometry={nodes.indicators_Car_Plastics_0.geometry}
                material={materials.Car_Plastics}
              />
              <mesh
                geometry={nodes["indicators_Material_#818_0"].geometry}
                material={materials.Material_818}
              />
              <mesh
                geometry={nodes["indicators_Material_#806_0"].geometry}
                material={materials.Material_806}
              />
            </group>
          </group>
          <group
            position={[0.066, -20.942, 25.749]}
            scale={[2.354, 1.677, 1.677]}
          >
            <group position={[-2.598, -5.197, 5.384]}>
              <mesh
                geometry={nodes["Object001_Material_#907_0"].geometry}
                material={materials.Material_907}
              />
              <mesh
                geometry={nodes["Object001_Material_#921_0"].geometry}
                material={materials.Material_921}
              />
              <mesh
                geometry={nodes["Object001_Material_#1003_0"].geometry}
                material={materials.Material_1003}
              />
              <mesh
                geometry={nodes["Object001_Material_#1015_0"].geometry}
                material={materials.Material_1015}
              />
              <mesh
                geometry={nodes["Object001_Material_#1079_0"].geometry}
                material={materials.Material_1079}
              />
              <mesh
                geometry={nodes["Object001_Material_#1094_0"].geometry}
                material={materials.Material_1094}
              />
              <mesh
                geometry={nodes["Object001_Material_#1110_0"].geometry}
                material={materials.Material_1110}
              />
              <mesh
                geometry={nodes["Object001_Material_#951_0"].geometry}
                material={materials.Material_951}
              />
              <mesh
                geometry={nodes["Object001_Material_#964_0"].geometry}
                material={materials.Material_964}
              />
              <mesh
                geometry={nodes["Object001_Material_#977_0"].geometry}
                material={materials.Material_977}
              />
              <mesh
                geometry={nodes["Object001_Material_#1039_0"].geometry}
                material={materials.Material_1039}
              />
              <mesh
                geometry={nodes["Object001_Material_#1052_0"].geometry}
                material={materials.Material_1052}
              />
              <mesh
                geometry={nodes["Object001_Material_#1065_0"].geometry}
                material={materials.Material_1065}
              />
              <mesh
                geometry={nodes["Object001_Material_#1154_0"].geometry}
                material={materials.Material_1154}
              />
              <mesh
                geometry={nodes["Object001_Material_#1172_0"].geometry}
                material={materials.Material_1172}
              />
              <mesh
                geometry={nodes["Object001_Material_#1191_0"].geometry}
                material={materials.Material_1191}
              />
              <mesh
                geometry={nodes["Object001_Material_#1210_0"].geometry}
                material={materials.Material_1210}
              />
              <mesh
                geometry={nodes["Object001_Material_#1271_0"].geometry}
                material={materials.Material_1271}
              />
              <mesh
                geometry={nodes["Object001_Material_#881_0"].geometry}
                material={materials.Material_881}
              />
            </group>
          </group>
          <group
            position={[19.095, -22.397, 33.594]}
            rotation={[-Math.PI / 2, 0, -1.484]}
          >
            <mesh
              geometry={nodes.rpmgauge_Car_Plastics_0.geometry}
              material={materials.Car_Plastics}
            />
            <mesh
              geometry={nodes["rpmgauge_Material_#1292_0"].geometry}
              material={materials.Material_1292}
            />
          </group>
          <group
            position={[9.911, -22.397, 33.594]}
            rotation={[-Math.PI / 2, 0, -1.484]}
          >
            <mesh
              geometry={nodes.speedgauge_Car_Plastics_0.geometry}
              material={materials.Car_Plastics}
            />
            <mesh
              geometry={nodes["speedgauge_Material_#1292_0"].geometry}
              material={materials.Material_1292}
            />
          </group>
          <group
            position={[14.441, -22.715, 33.962]}
            rotation={[-1.396, 0, -Math.PI]}
            scale={0.614}
          >
            <group position={[-1.458, 0.823, -0.287]}>
              <mesh
                geometry={nodes.othergauges_Car_Plastics_0.geometry}
                material={materials.Car_Plastics}
              />
              <mesh
                geometry={nodes["othergauges_Material_#1292_0"].geometry}
                material={materials.Material_1292}
              />
            </group>
          </group>
          <group
            position={[3.55, -13.601, 19.756]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
            scale={[0.953, 0.937, 1]}
          >
            <mesh
              geometry={nodes.handbrake_Car_Plastics_0.geometry}
              material={materials.Car_Plastics}
            />
            <mesh
              geometry={nodes["handbrake_Material_#205_0"].geometry}
              material={materials.Material_205}
            />
          </group>
          <group
            position={[0.319, -3.238, 46.774]}
            scale={[0.467, 0.467, 0.118]}
          >
            <group position={[32.936, 0.817, 1.782]}>
              <mesh
                geometry={nodes["subvisors_Material_#205_0"].geometry}
                material={materials.Material_205}
              />
              <mesh
                geometry={nodes["subvisors_Material_#1554_0"].geometry}
                material={materials.Material_1554}
              />
            </group>
          </group>
          <group
            position={[0.015, -10.819, 42.794]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={1.029}
          >
            <mesh
              geometry={nodes.Plane001_Glass_Mirror0_0.geometry}
              material={materials.Glass_Mirror0}
            />
            <mesh
              geometry={nodes.Plane001_Car_Plastics_0.geometry}
              material={materials.Car_Plastics}
            />
          </group>
          <group
            position={[-28.131, -21.674, 28.967]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
          >
            <group position={[-30.417, -15.772, -28.722]}>
              <mesh
                geometry={nodes.rightdoor_Carpaint_Flakes_Ruby_0.geometry}
                material={materials.Carpaint_Flakes_Ruby}
              >
                <meshStandardMaterial
                  color={props.color}
                  metalness={0.6}
                  roughness={0.2}
                />
              </mesh>
              <mesh
                geometry={nodes.rightdoor_Car_Plastics_0.geometry}
                material={materials.Car_Plastics}
              />
              <mesh
                geometry={nodes.rightdoor_Leather_Top_Grain_Black_0.geometry}
                material={materials.Leather_Top_Grain_Black}
              />
              <mesh
                geometry={nodes["rightdoor_Material_#217_0"].geometry}
                material={materials.Material_217}
              />
              <mesh
                geometry={nodes["rightdoor_Material_#513_0"].geometry}
                material={materials.Material_513}
              />
              <mesh
                geometry={nodes.rightdoor_Glass_Mirror_0.geometry}
                material={materials.Glass_Mirror}
              />
              <mesh
                geometry={nodes["rightdoor_Material_#300_0"].geometry}
                material={materials.Material_300}
              />
            </group>
          </group>
          <group
            position={[31.864, 45.727, 13.278]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
            scale={[1.01, 1.01, 1.268]}
          >
            <group position={[-1.918, -7.572, 1.382]}>
              <mesh
                geometry={nodes["FrdPerofrmcRim001_Material_#205_0"].geometry}
                material={materials.Material_205}
              />
              <mesh
                geometry={nodes.FrdPerofrmcRim001_Aluminium_Clean2_0.geometry}
                material={materials.Aluminium_Clean2}
              />
              <mesh
                geometry={nodes.FrdPerofrmcRim001_Aluminium_Clean3_0.geometry}
                material={materials.Aluminium_Clean3}
              />
            </group>
          </group>
          <group
            position={[29.08, 45.733, 13.239]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
            scale={[1, 1, 1.095]}
          >
            <mesh
              geometry={nodes.tire001_rubbr1_0.geometry}
              material={materials.rubbr1}
            />
            <mesh
              geometry={nodes.tire001_rubbr2_0.geometry}
              material={materials.rubbr2}
            />
          </group>
          <group
            position={[-31.177, 45.714, 13.278]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            scale={[1.01, 1.01, 1.268]}
          >
            <group position={[-1.918, -7.572, 1.382]}>
              <mesh
                geometry={nodes["FrdPerofrmcRim002_Material_#205_0"].geometry}
                material={materials.Material_205}
              />
              <mesh
                geometry={nodes.FrdPerofrmcRim002_Aluminium_Clean2_0.geometry}
                material={materials.Aluminium_Clean2}
              />
              <mesh
                geometry={nodes.FrdPerofrmcRim002_Aluminium_Clean3_0.geometry}
                material={materials.Aluminium_Clean3}
              />
            </group>
          </group>
          <group
            position={[-31.177, -51.982, 13.278]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            scale={[1.01, 1.01, 1.268]}
          >
            <group position={[-1.918, -7.572, 1.382]}>
              <mesh
                geometry={nodes["FrdPerofrmcRim003_Material_#205_0"].geometry}
                material={materials.Material_205}
              />
              <mesh
                geometry={nodes.FrdPerofrmcRim003_Aluminium_Clean2_0.geometry}
                material={materials.Aluminium_Clean2}
              />
              <mesh
                geometry={nodes.FrdPerofrmcRim003_Aluminium_Clean3_0.geometry}
                material={materials.Aluminium_Clean3}
              />
            </group>
          </group>
          <group
            position={[-28.393, 45.707, 13.239]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            scale={[1, 1, 1.095]}
          >
            <mesh
              geometry={nodes.tire002_rubbr1_0.geometry}
              material={materials.rubbr1}
            />
            <mesh
              geometry={nodes.tire002_rubbr2_0.geometry}
              material={materials.rubbr2}
            />
          </group>
          <group
            position={[-28.393, -51.988, 13.239]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            scale={[1, 1, 1.095]}
          >
            <mesh
              geometry={nodes.tire003_rubbr1_0.geometry}
              material={materials.rubbr1}
            />
            <mesh
              geometry={nodes.tire003_rubbr2_0.geometry}
              material={materials.rubbr2}
            />
          </group>
          <group
            position={[14.541, -77.822, 24.242]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.607}
          >
            <mesh
              geometry={nodes.Cylinder003_Car_Plastics_0.geometry}
              material={materials.Car_Plastics}
            />
            <mesh
              geometry={nodes["Cylinder003_Material_#1611_0"].geometry}
              material={materials.Material_1611}
            />
            <mesh
              geometry={nodes.Cylinder003_Glass_Clear_0.geometry}
              material={materials.Glass_Clear}
            />
          </group>
          <group
            position={[-22.511, 76.282, 12.092]}
            rotation={[1.506, 0, 0]}
            scale={[0.475, 0.48, 0.403]}
          >
            <mesh
              geometry={nodes["exhaust_tip_Material_#746_0"].geometry}
              material={materials.Material_746}
            />
            <mesh
              geometry={nodes["exhaust_tip_Material_#745_0"].geometry}
              material={materials.Material_745}
            />
            <mesh
              geometry={nodes["exhaust_tip_Material_#742_0"].geometry}
              material={materials.Material_742}
            />
          </group>
          <mesh
            geometry={nodes.sideskirt_Carpaint_Flakes_Ruby_0.geometry}
            material={materials.Carpaint_Flakes_Ruby}
            position={[29.863, -2.631, 8.561]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
            scale={[1, 1, 0.919]}
          >
            <meshStandardMaterial
              color={props.color}
              metalness={0.6}
              roughness={0.2}
            />
          </mesh>
          <mesh
            geometry={nodes.bottm_fullblack_0.geometry}
            material={materials.fullblack}
            position={[0, -52.043, 13.195]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.gaugesilv_Aluminium_Clean1_0.geometry}
            material={materials.Aluminium_Clean1}
            position={[19.062, -23.34, 33.771]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={[1.226, 1.226, 1.469]}
          />
          <mesh
            geometry={nodes.steeringcolumn__0.geometry}
            material={materials.steeringcolumn__0}
            position={[14.471, -26.839, 30.24]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={[0.939, 1.008, 1.008]}
          />
          <mesh
            geometry={nodes.radiator_Aluminium_Clean_0.geometry}
            material={materials.Aluminium_Clean}
            position={[1.096, -73.465, 11.496]}
            scale={[1, 0.132, 1]}
          />
          <mesh
            geometry={nodes.fronteng_fullblack_0.geometry}
            material={materials.fullblack}
            position={[-0.651, -68.798, 18.694]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            geometry={nodes["Box003_Material_#1415_0"].geometry}
            material={materials.Material_1415}
            position={[0.386, -3.922, 47.146]}
            scale={[0.474, 0.403, 0.403]}
          />
          <mesh
            geometry={nodes.pedals_GlossBlack_0.geometry}
            material={materials.GlossBlack}
            position={[9.775, -28.593, 16.729]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={0.436}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/mustang-2005.glb");
