/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/mustang-shelby-gt500.glb 
Author: Jiaxing (https://sketchfab.com/saitoyang)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ford-mustang-shelby-gt500-0eaa7a16796540f29461ddae05ecdeb3
Title: Ford Mustang Shelby GT500
*/

import React, { useLayoutEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Model(props) {
  const { scene } = useGLTF("/mustang-shelby-gt500.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  useLayoutEffect(() => {
    Object.entries(materials).forEach(([name, material]) => {
      const lowerName = name.toLowerCase();

      if (lowerName.includes("car")) {
        material.color.set(props.color || "#173F5F");
        material.metalness = 0.6;
        material.roughness = 0.2;
      }
    });
  }, [materials, props.color]);
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <primitive object={nodes._rootJoint} />
          <group position={[-1.782, 0, 0]}>
            <group
              position={[2.622, -3.884, 0.62]}
              rotation={[2.153, 0, 0]}
              scale={1.135}
            >
              <mesh
                geometry={nodes.GT500WheelFtL_lambert1_0.geometry}
                material={materials.lambert1}
              />
              <mesh
                geometry={nodes.GT500WheelFtL_glossblack_0.geometry}
                material={materials.glossblack}
              />
              <mesh
                geometry={nodes.GT500WheelFtL_tire_0.geometry}
                material={materials.tire}
              />
              <mesh
                geometry={nodes.GT500WheelFtL_plate_0.geometry}
                material={materials.plate}
              />
            </group>
            <mesh
              geometry={nodes.GT500WheelBrakeBkL_brake_0.geometry}
              material={materials.brake}
              position={[0.399, 1.48, 0.326]}
              scale={1.031}
            />
          </group>
        </group>
      </group>
    </group>
  );
}
